package com.hellomydoc.doctor

enum class PAGE_TYPE{
    FRAGMENT,
    ACTIVITY
}

enum class PAGE(val pageType: PAGE_TYPE) {
    CHAT(PAGE_TYPE.ACTIVITY),
    VIDEO_CALLING(PAGE_TYPE.ACTIVITY),
    APPOINTMENT_HISTORY(PAGE_TYPE.ACTIVITY),
    HOME_ROOT(PAGE_TYPE.ACTIVITY),
    ADD_PRESCRIPTION(PAGE_TYPE.ACTIVITY),
    PRESCRIPTIONS(PAGE_TYPE.ACTIVITY),
    HOME(PAGE_TYPE.FRAGMENT),
    VIDEO_CONSULTATIONS(PAGE_TYPE.FRAGMENT),
    VOICE_CONSULTATION(PAGE_TYPE.FRAGMENT),
    CHAT_CONSULTATIONS(PAGE_TYPE.FRAGMENT),
}